### ISSUE TITLE
Phone number can't be fetched

### ISSUE THREAD

**Issue by margiPalanBVI** [yonat/ContactsChangeNotifier#2]
Hello, the demo is working fine I tried to make in swift by installing pod and swift also works fine but the issue is how can I get the contact number? if anyone have idea about it let me know

**Comment by yonat** [comment]
Pass `CNContactPhoneNumbersKey` into `additionalContactKeyDescriptors` like so:

```swift
let contactsChangeNotifier = try! ContactsChangeNotifier(
    store: myCNContactStore,
    fetchRequest: .fetchRequest(additionalContactKeyDescriptors: [CNContactPhoneNumbersKey as CNKeyDescriptor])
)
```
