### ISSUE TITLE
CNContactStore.currentHistoryToken is alway nil on iOS 13 and iOS 14

### ISSUE THREAD

**Issue by phatnguyen1006** [yonat/ContactsChangeNotifier#3]
Everything is good til I test on my iPhone iOS 13.2.
CNContactStore.currentHistoryToken always empty.
Can you add supporting iOS list into your doc.
Thanks for reading

**Comment by phatnguyen1006** [comment]
Same to 14.0

**Comment by yonat** [comment]
I'll need running code to debug this...
Please create a minimal project that reproduces this problem, create a github project with its code, and link to it here. (See https://ootips.org/yonat/repex/)

**Comment by phatnguyen1006** [comment]
Thanks for replying back

@yonat nothing change to reproduce, just run your example in iOS 13.x or iOS 14.x. 
The functions are not right anymore.

**Comment by phatnguyen1006** [comment]
I found an answer on Apple Forums by an Apple Engineer. [Link here](https://developer.apple.com/forums/thread/696387)
Its a bug in Swift.

So we can take currentHistoryToken from ObjC or we can get currentHistoryToken from [CNFetchResult (from Apple Docs)](https://developer.apple.com/documentation/contacts/cncontactstore/3113739-currenthistorytoken)

I have taken it from ObjC and it worked. My code in PR (#4)

Thanks for supporting

**Comment by phatnguyen1006** [comment]
After double checked, I see store.currentHistoryToken nil from both ObjC and Swift (on iOS 13.x and 14.x).
I will wait for you confirm and update (if can).
Thanks

**Comment by yonat** [comment]
Sorry for responding late, I will not be unavailable until Jul-14.

**Comment by phatnguyen1006** [comment]
@yonat have any update?

**Comment by yonat** [comment]
Didn’t have a chance to check yet, will take a look next weekend.

**Comment by yonat** [comment]
Just checked this, I don't think i'll be able to support iOS 13 and 14. 😞

I'll raise the minimum target to iOS 15.
